# -*- coding: utf-8 -*-
"""clase 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vfCmGr4KmcCST7ZvS0p3Yahk8TO_lfUJ

1.4 Hola Mundo con Python
"""

print("Hola Mundo")

"""1.5 Actividad: Saludar con Python: Hacerlo en la terminal de Python"""

nombre = input("¿Cómo te llamas? ")
print("¡Hola,", nombre, "! Bienvenido a Python.")