# -*- coding: utf-8 -*-
"""clase 2 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fJ1E-z-hRa3HGt5p9Ahkeg2uMKGkGeiX
"""

miVariable = 3
print(miVariable)
miVariable = "Hola a todos los alumnos de la tecnicatura"
print(miVariable)
miVariable = 3.5
print(miVariable)
x = 10
y = 2
z = x + y
print(id (x))
# Las literales se escriben x104, 848, a variable z = x168
print(id (y))
print(id(z))